# Generated by Django 6.1 on 2026-08-11 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attractions', '0001_initial'),
        ('destinations', '0001_initial'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alt text')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='caption')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image', models.ImageField(upload_to='attractions/', verbose_name='image')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='attractions.attraction')),
            ],
            options={
                'verbose_name': 'attraction image',
                'verbose_name_plural': 'attraction images',
                'indexes': [models.Index(fields=['attraction', 'is_primary', 'display_order'], name='images_attr_attract_478ab1_idx')],
            },
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alt text')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='caption')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image', models.ImageField(upload_to='destinations/', verbose_name='image')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'destination image',
                'verbose_name_plural': 'destination images',
                'indexes': [models.Index(fields=['destination', 'is_primary', 'display_order'], name='images_dest_destina_f65315_idx')],
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alt text')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='caption')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='display order')),
                ('is_primary', models.BooleanField(default=False, verbose_name='is primary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('image', models.ImageField(upload_to='hotels/', verbose_name='image')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'hotel image',
                'verbose_name_plural': 'hotel images',
                'indexes': [models.Index(fields=['hotel', 'is_primary', 'display_order'], name='images_hote_hotel_i_a9d585_idx')],
            },
        ),
    ]
