# Generated by Django 6.1 on 2026-08-11 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attractions', '0001_initial'),
        ('destinations', '0001_initial'),
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('attraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attractions.attraction')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destinations.destination')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wishlist entry',
                'verbose_name_plural': 'wishlist entries',
                'indexes': [models.Index(fields=['user', 'created_at'], name='wishlist_wi_user_id_8199a6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('destination__isnull', False)), fields=('user', 'destination'), name='unique_user_destination'), models.UniqueConstraint(condition=models.Q(('hotel__isnull', False)), fields=('user', 'hotel'), name='unique_user_hotel'), models.UniqueConstraint(condition=models.Q(('attraction__isnull', False)), fields=('user', 'attraction'), name='unique_user_attraction')],
            },
        ),
    ]
