# Generated by Django 6.1 on 2026-08-11 06:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('short_description', models.CharField(max_length=255, verbose_name='short description')),
                ('description', models.TextField(verbose_name='description')),
                ('category', models.CharField(choices=[('HISTORICAL', 'Historical'), ('CULTURAL', 'Cultural'), ('NATURE', 'Nature'), ('ADVENTURE', 'Adventure'), ('RELIGIOUS', 'Religious'), ('MUSEUM', 'Museum'), ('BEACH', 'Beach'), ('PARK', 'Park'), ('SHOPPING', 'Shopping'), ('ENTERTAINMENT', 'Entertainment'), ('OTHER', 'Other')], max_length=20, verbose_name='category')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude')),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='entry fee')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('estimated_duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='estimated duration (mins)')),
                ('best_time_to_visit', models.CharField(blank=True, max_length=255, verbose_name='best time to visit')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='opening time')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='closing time')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='average rating')),
                ('popularity_score', models.IntegerField(default=0, verbose_name='popularity score')),
                ('accessibility', models.JSONField(blank=True, default=dict, verbose_name='accessibility info')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10, verbose_name='status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'attraction',
                'verbose_name_plural': 'attractions',
                'indexes': [models.Index(fields=['destination', 'slug'], name='attractions_destina_e31b5f_idx'), models.Index(fields=['category'], name='attractions_categor_2f4c97_idx'), models.Index(fields=['city'], name='attractions_city_4eeec1_idx'), models.Index(fields=['country'], name='attractions_country_8f9bdc_idx'), models.Index(fields=['status'], name='attractions_status_aea291_idx'), models.Index(fields=['is_featured'], name='attractions_is_feat_b8192f_idx'), models.Index(fields=['popularity_score'], name='attractions_popular_a22a93_idx'), models.Index(fields=['entry_fee'], name='attractions_entry_f_52d5fa_idx')],
            },
        ),
    ]
