# Generated by Django 5.2.6 on 2026-08-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_attraction_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, verbose_name='image URL'),
        ),
    ]
