# Generated by Django 6.1 on 2026-08-11 05:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('short_description', models.CharField(max_length=255, verbose_name='short description')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude')),
                ('star_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='star rating')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='average rating')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price per night')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('amenities', models.JSONField(blank=True, default=list, verbose_name='amenities')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10, verbose_name='status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'hotel',
                'verbose_name_plural': 'hotels',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('room_type', models.CharField(choices=[('STANDARD', 'Standard'), ('DELUXE', 'Deluxe'), ('SUITE', 'Suite'), ('FAMILY', 'Family')], max_length=20, verbose_name='room type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='capacity')),
                ('bed_type', models.CharField(blank=True, max_length=50, verbose_name='bed type')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price per night')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('total_rooms', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='total rooms')),
                ('available_rooms', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='available rooms')),
                ('amenities', models.JSONField(blank=True, default=list, verbose_name='amenities')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
            },
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['destination', 'slug'], name='hotels_hote_destina_dee444_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['city'], name='hotels_hote_city_da33bc_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['country'], name='hotels_hote_country_968a79_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['status'], name='hotels_hote_status_218965_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['star_rating'], name='hotels_hote_star_ra_e9d0d2_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['is_featured'], name='hotels_hote_is_feat_c611e4_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hotel', 'status'], name='hotels_room_hotel_i_aa593c_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_type'], name='hotels_room_room_ty_c015b5_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['price_per_night'], name='hotels_room_price_p_ddffaf_idx'),
        ),
    ]
