# Generated by Django 6.1 on 2026-08-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='review count'),
        ),
    ]
