# Generated by Django 5.2.6 on 2026-08-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('hotels', '0003_hotel_image_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotel',
            unique_together={('destination', 'name')},
        ),
    ]
