# Generated by Django 6.1 on 2026-08-11 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='region')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('description', models.TextField(verbose_name='description')),
                ('short_description', models.CharField(max_length=255, verbose_name='short description')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude')),
                ('cover_image_url', models.URLField(blank=True, verbose_name='cover image URL')),
                ('best_time_to_visit', models.CharField(blank=True, max_length=255, verbose_name='best time to visit')),
                ('average_budget', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='average budget')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10, verbose_name='status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'destination',
                'verbose_name_plural': 'destinations',
                'indexes': [models.Index(fields=['slug'], name='destination_slug_528bb8_idx'), models.Index(fields=['city'], name='destination_city_ec88bc_idx'), models.Index(fields=['country'], name='destination_country_2ade19_idx'), models.Index(fields=['status'], name='destination_status_39abee_idx'), models.Index(fields=['is_featured'], name='destination_is_feat_54f559_idx')],
            },
        ),
    ]
