# Generated by Django 6.1 on 2026-08-11 08:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attractions', '0002_attraction_review_count'),
        ('hotels', '0002_hotel_review_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('comment', models.TextField(verbose_name='comment')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('attraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attractions.attraction')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'indexes': [models.Index(fields=['hotel', 'status'], name='reviews_rev_hotel_i_e7968d_idx'), models.Index(fields=['attraction', 'status'], name='reviews_rev_attract_0132e1_idx'), models.Index(fields=['user', 'created_at'], name='reviews_rev_user_id_35ef9b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('hotel__isnull', False)), fields=('user', 'hotel'), name='unique_user_hotel_review'), models.UniqueConstraint(condition=models.Q(('attraction__isnull', False)), fields=('user', 'attraction'), name='unique_user_attraction_review')],
            },
        ),
    ]
