# Generated by Django 6.1 on 2026-08-11 09:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDNACategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'travel DNA category',
                'verbose_name_plural': 'travel DNA categories',
                'indexes': [models.Index(fields=['slug'], name='travel_dna__slug_8c118d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserTravelDNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='score')),
                ('confidence', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='confidence')),
                ('last_calculated_at', models.DateTimeField(auto_now=True, verbose_name='last calculated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_dna.traveldnacategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_dna', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user travel DNA',
                'verbose_name_plural': 'user travel DNA',
                'indexes': [models.Index(fields=['user', 'score'], name='travel_dna__user_id_9720f9_idx')],
                'unique_together': {('user', 'category')},
            },
        ),
    ]
