# Generated by Django 6.1 on 2026-08-11 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_attraction_review_count'),
        ('destinations', '0001_initial'),
        ('hotels', '0002_hotel_review_count'),
        ('travel_dna', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelBehaviorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('DESTINATION_VIEW', 'Destination View'), ('HOTEL_VIEW', 'Hotel View'), ('ATTRACTION_VIEW', 'Attraction View'), ('SEARCH', 'Search'), ('WISHLIST_ADD', 'Wishlist Add'), ('WISHLIST_REMOVE', 'Wishlist Remove'), ('REVIEW_SUBMITTED', 'Review Submitted')], max_length=20, verbose_name='event type')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('attraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attractions.attraction')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destinations.destination')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'travel behavior event',
                'verbose_name_plural': 'travel behavior events',
                'indexes': [models.Index(fields=['user', 'created_at'], name='travel_dna__user_id_074828_idx'), models.Index(fields=['user', 'event_type'], name='travel_dna__user_id_383506_idx')],
            },
        ),
    ]
